Added Docker stage for building debian packages as part of Github Actions integration.

diff --git a/edgefirst_msgs/debian/rules b/edgefirst_msgs/debian/rules
--- a/edgefirst_msgs/debian/rules
+++ b/edgefirst_msgs/debian/rules
@@ -6,6 +6,11 @@
 # dh-make output file, you may use that output file without restriction.
 # This special exception was added by Craig Small in version 0.37 of dh-make.
 
+TAG := $(shell git describe --tags | cut -b2-)
+COMMENT := $(shell git tag -l -n1 $(TAG))
+BUILD_NUMBER ?= 0
+ROS_DISTRO ?= humble
+
 # Uncomment this to turn on verbose mode.
 export DH_VERBOSE=1
 # TODO: remove the LDFLAGS override.  It's here to avoid esoteric problems
@@ -13,7 +18,7 @@ export DH_VERBOSE=1
 #  https://code.ros.org/trac/ros/ticket/2977
 #  https://code.ros.org/trac/ros/ticket/3842
 export LDFLAGS=
-export PKG_CONFIG_PATH=/opt/ros/humble/lib/pkgconfig
+export PKG_CONFIG_PATH=/opt/ros/$(ROS_DISTRO)/lib/pkgconfig
 # Explicitly enable -DNDEBUG, see:
 # 	https://github.com/ros-infrastructure/bloom/issues/327
 export DEB_CXXFLAGS_MAINT_APPEND=-DNDEBUG
@@ -30,38 +35,44 @@ override_dh_auto_configure:
 	# In case we're installing to a non-standard location, look for a setup.sh
 	# in the install tree and source it.  It will set things like
 	# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
-	if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi && \
+	if [ -f "/opt/ros/$(ROS_DISTRO)/setup.sh" ]; then . "/opt/ros/$(ROS_DISTRO)/setup.sh"; fi && \
 	dh_auto_configure -- \
-		-DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
-		-DAMENT_PREFIX_PATH="/opt/ros/humble" \
-		-DCMAKE_PREFIX_PATH="/opt/ros/humble" \
+		-DCMAKE_INSTALL_PREFIX="/opt/ros/$(ROS_DISTRO)" \
+		-DAMENT_PREFIX_PATH="/opt/ros/$(ROS_DISTRO)" \
+		-DCMAKE_PREFIX_PATH="/opt/ros/$(ROS_DISTRO)" \
 		$(BUILD_TESTING_ARG)
 
 override_dh_auto_build:
 	# In case we're installing to a non-standard location, look for a setup.sh
 	# in the install tree and source it.  It will set things like
 	# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
-	if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi && \
+	if [ -f "/opt/ros/$(ROS_DISTRO)/setup.sh" ]; then . "/opt/ros/$(ROS_DISTRO)/setup.sh"; fi && \
 	dh_auto_build
 
 override_dh_auto_test:
 	# In case we're installing to a non-standard location, look for a setup.sh
 	# in the install tree and source it.  It will set things like
 	# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
-	echo -- Running tests. Even if one of them fails the build is not canceled.
-	if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi && \
-	dh_auto_test || true
+	# echo -- Running tests. Even if one of them fails the build is not canceled.
+	# if [ -f "/opt/ros/$(ROS_DISTRO)/setup.sh" ]; then . "/opt/ros/$(ROS_DISTRO)/setup.sh"; fi && \
+	# dh_auto_test || true
 
 override_dh_shlibdeps:
 	# In case we're installing to a non-standard location, look for a setup.sh
 	# in the install tree and source it.  It will set things like
 	# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
-	if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi && \
-	dh_shlibdeps -l$(CURDIR)/debian/ros-humble-edgefirst-msgs//opt/ros/humble/lib/:$(CURDIR)/debian/ros-humble-edgefirst-msgs//opt/ros/humble/opt/edgefirst_msgs/lib/
+	if [ -f "/opt/ros/$(ROS_DISTRO)/setup.sh" ]; then . "/opt/ros/$(ROS_DISTRO)/setup.sh"; fi && \
+	dh_shlibdeps -l$(CURDIR)/debian/ros-$(ROS_DISTRO)-edgefirst-msgs//opt/ros/$(ROS_DISTRO)/lib/:$(CURDIR)/debian/ros-$(ROS_DISTRO)-edgefirst-msgs//opt/ros/$(ROS_DISTRO)/opt/edgefirst_msgs/lib/
 
 override_dh_auto_install:
 	# In case we're installing to a non-standard location, look for a setup.sh
 	# in the install tree and source it.  It will set things like
 	# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
-	if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi && \
+	if [ -f "/opt/ros/$(ROS_DISTRO)/setup.sh" ]; then . "/opt/ros/$(ROS_DISTRO)/setup.sh"; fi && \
 	dh_auto_install
+
+version:
+	$(RM) debian/changelog
+	dch --create --distribution stable \
+		--package ros-$(ROS_DISTRO)-edgefirst-msgs \
+		--newversion $(TAG)-$(BUILD_NUMBER) "$(COMMENT)"
